language: csharp
dotnet: 2.1.500

before_script:
  - nvm install 8.11.4
  - nvm use 8.11.4
  #install yarn globally
  - npm install -g yarn
  - npm rebuild node-sass
  - yarn

cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master