language: node_js
dotnet: 
- "1.1.5"
node_js:
- "8.11.4"
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master